using System.ComponentModel;
using AIBridge.Core.Services;
using AIBridge.Mcp.Providers;
using ModelContextProtocol.Server;

namespace AIBridge.Mcp.Tools;

public class ApplyAiResponseTool(ApplyService applyService, StringLogger logger)
{
    [McpServerTool(Name = "apply_ai_response")]
    [Description("Applies an AI-generated XML response to the local codebase. Supports file requests, code edits, index creation, and index updates.")]
#pragma warning disable CA1707 // Identifiers should not contain underscores (needed for MCP tool schema)
    public async Task<string> ExecuteAsync(
        [Description("The raw XML response generated by the AI")] string xml_content,
        CancellationToken cancellationToken)
#pragma warning restore CA1707
    {
        // logger is now scoped per request, so no need to call logger.Clear()
        var root = Environment.CurrentDirectory; // Uses the directory where the MCP server was started
        
        var result = await applyService.ExecuteAsync(xml_content, root, false);

        if (result.ContextPayload != null)
        {
            return result.ContextPayload;
        }

        var logs = logger.GetLogs();
        if (!result.IsSuccess)
        {
            return $"Failed:\n{result.ErrorMessage}\n\nLogs:\n{logs}";
        }

        return $"Success.\n\nLogs:\n{logs}";
    }
}
